In [1]:
import os
import scipy
import numpy as np
import pandas as pd
import re

In [2]:
directory='//Users//prathamagrawal//Desktop//projects//ECG//dataset'

In [9]:
def dataloader(directory):
    l=[]
    for filename in os.listdir(directory):
        if filename.endswith('.mat'):
            filename = directory + "/" + filename
            temp=scipy.io.loadmat(filename)
            temp=np.array(temp['val'])
            l.append(temp)
    return l

l=dataloader(directory)

In [15]:
print(l[0])

[[ -15  -44    0 ...  -15  -10   -5]
 [ -68  -93  -44 ...    5  -20   10]
 [ -54  -49  -44 ...   20  -10   15]
 ...
 [-195 -210 -195 ...   15   24   59]
 [-254 -268 -259 ...  -39  -24   20]
 [-264 -283 -283 ...  -34  -24    5]]


In [40]:
import wfdb
signals,fields=wfdb.rdsamp('dataset/JS00001')
print(signals.shape)
fiels2=fields['comments']
re.sub('Sex: ','','Sex: Male')
print(fields)

(5000, 12)
{'fs': 500, 'sig_len': 5000, 'n_sig': 12, 'base_date': None, 'base_time': datetime.time(0, 0, 23), 'units': ['mV', 'mV', 'mV', 'mV', 'mV', 'mV', 'mV', 'mV', 'mV', 'mV', 'mV', 'mV'], 'sig_name': ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'], 'comments': ['Age: 85', 'Sex: Male', 'Dx: 164889003,59118001,164934002', 'Rx: Unknown', 'Hx: Unknown', 'Sx: Unknown']}


In [29]:
def return_sex(text):
   text=re.sub('Sex: ','',text)
   return text

In [30]:
def return_age(text):
   text=re.sub('Age: ','',text)
   return text

In [73]:
def read_data(directory):
    data_signal=[]
    data_attribute=[]
    sex=[]
    age=[]
    for filename in os.listdir(directory):
        if filename.endswith('.hea'):
            filename=directory+'/'+filename
            filename=re.sub('.hea','',filename)
            signals,fields=wfdb.rdsamp(filename)
            data_signal.append(signals)
            comments=fields['comments']
            agev=return_age(comments[0])
            age.append(agev)
            sexv=return_sex(comments[1])
            sex.append(sexv)
            data_attribute.append(age)
            data_attribute.append(sex)
    return data_signal,age,sex

In [74]:
data_signal,age,sex=read_data(directory)

In [79]:
d={"signals":data_signal,"age":age,"sex":sex}
data=pd.DataFrame(d)
data

signals age     sex
0      [[-0.107, -0.112, -0.005, 0.112, -0.054, -0.05...  68    Male
1      [[0.02, -0.02, -0.039, 0.0, 0.029, -0.029, 0.0...  27  Female
2      [[-0.034, -0.112, -0.078, 0.073, 0.02, -0.098,...  17    Male
3      [[-0.215, -0.01, 0.205, 0.112, -0.21, 0.098, 0...  60    Male
4      [[-0.068, -0.039, 0.029, 0.054, -0.049, -0.005...  76    Male
...                                                  ...  ..     ...
10242  [[-0.127, -0.264, -0.137, 0.195, 0.005, -0.2, ...  63    Male
10243  [[-0.063, -0.059, 0.005, 0.063, -0.034, -0.029...  77    Male
10244  [[-0.171, 1.459, 1.63, -0.644, -0.903, 1.542, ...  27    Male
10245  [[-0.01, -0.073, -0.063, 0.044, 0.024, -0.068,...  69    Male
10246  [[-0.034, -0.068, -0.034, 0.054, 0.0, -0.054, ...  89    Male

[10247 rows x 3 columns]

In [80]:
data.to_csv("Dataset.csv")

